### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Around999People** [Seedmanc/Booru-mass-uploader#10]
When I click on the mass upload link I just get a white screen. It worked for me before.

**Comment by Seedmanc** [comment]
Which booru, which browser, have you updated the user.js or are you still using the old version?

**Comment by ProximaNova** [comment]
Same with me on both Firefox and Chrome: both private and not on all software versions of Gelbooru. Previously today I had mass uploaded a few folders to a few boorus successfully but now it has faltered (even after restarting my computer). I have also used inspect element to insert `index.html` but I never get past `spinner.gif`

Also if Gelbooru software then the upload page is at `index.php?page=post&s=mass_upload`
else if Danbooru software the the upload page is mainly at `uploads/new`

**Update:** From Firefox > Inspect element > Security: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://crossorigin.me/http://seedmanc.github.io/Booru-mass-uploader/index.html?r=0.07841655538834225. (Reason: CORS header 'Access-Control-Allow-Origin' missing)." (However, this may be a transient error.)

**Comment by Seedmanc** [comment]
Well this just gets weirder and weirder. The URL where the "Mass uploader" text links doesn't matter, it's just some place that doesn't exist on the booru so we can inject our code there. Actual API requests are computed internally.

It's quite strange that FF blocks CORS to a site that is made with the very purpose of fixing that. FF being itself, as always.

Considering that OP mentions white screen he most likely uses it on gelbooru engine.

Try removing the part that generates random number from the request to the index.html, just a random thought here.

**Comment by ProximaNova** [comment]
- If the location doesn't matter then maybe for Danbooru set it to `uploads/mass` to be in line with the site. Or set all software versions locations to `example.com/mass-upload`
- I tried removing the random generator part at `index.html?r=' + Math.random()` but it fixed nothing.

**Comment by Seedmanc** [comment]
Navigating to /mass-upload on *.booru.org causes redirection to booru.org's 404 page and that's not cool.

**Comment by ProximaNova** [comment]
It works at `index.php?s=mass_upload` though, but the CSS is messed up.

**Comment by Seedmanc** [comment]
I wonder if crossorigin.me has a limit on the amount of connections/usages per day. You said that you encountered problems after uploading folders, while I hardly ever upload anything and I never have problems. 

On the other hand, the uploading itself and communications with booru apis does not require crossorigin service, only reloading the page does, so maybe it's not the case. I wish people were more verbose in their reports.

**Comment by Seedmanc** [comment]
Judging by booru forum thread the issue ceased to be. Thus closed, but the discussion can continue.

**Comment by Seedmanc** [comment]
Another possibility might be loading of crossorigin.me or the scripts with protocol being different from current site. If you have HTTPSeverywhere or something like that,browser might refuse to load http:// linked resources. But thal would be consistent and not random, I would expect.

**Comment by Seedmanc** [comment]
Actually, this seemed to be an issue with crossorigin.me availability. I've just got a couple of 522 errors with the site, apparently it was under high load. In such moments it would be unable to return the page, thus showing the white screen.
Try later.
