### ISSUE TITLE
Detect if site is booru or not.

### ISSUE THREAD

**Issue by spiral6** [Seedmanc/Booru-mass-uploader#15]
I have a server of mine setup with gelbooru, at address http://teamconege.cf/gallery, but the userscript doesn't detect that it is a booru site, and thus doesn't enable the option to mass upload.

**Comment by Seedmanc** [comment]
Add "// @include		http://teamconege.cf/*" to a list of includes in the header of the script.

**Comment by spiral6** [comment]
Thank you, that worked out very well.
