### ISSUE TITLE
Issue with null source.

### ISSUE THREAD

**Issue by Iratu** [Seedmanc/Booru-mass-uploader#18]
G'day Seedmanc,

One of my users came to me saying that the latest update to the booru I run caused this mass uploader to stop working see: https://allthefallen.ninja/index.php?/topic/6239-atf-mass-upload-broken/#entry194625 WARNING: NSFW.

I've solved the issue by adding source to the Danbooru config see; https://github.com/Iratu/Booru-mass-uploader/blob/gh-pages/js/booru-params.js

I will report this to Danbooru as well but I'm not sure if they'll fix it.

**Comment by Seedmanc** [comment]
Hello and thanks for reporting. It seems Danbooru might have fixed it already https://github.com/r888888888/danbooru/pull/3169 but I'll add your fix anyway, since the source field shouldn't be omitted.

**Comment by Iratu** [comment]
Yeah I reported it there as well, and they fixed it today :)
