### ISSUE TITLE
Script doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [Seedmanc/Booru-mass-uploader#21]
The script doesn't seem to work anymore. The mass upload key hasn't appeared since the update to the script 19 days ago or so.

**Comment by Seedmanc** [comment]
What booru are you using where it doesn't work?

**Comment by ghost** [comment]
I use charri.booru.org but I haven't seen it pop up on any other booru's. A long time ago I accidently made a branch of it where I put in my charri booru before I realized you didn't need to and it works fine without the recent update. And with the recent one, putting in the include thing doesn't help

**Comment by Seedmanc** [comment]
Right, thanks for reporting, should be fixed now.
