### ISSUE TITLE
It won't upload anything...

### ISSUE THREAD

**Issue by owengraven** [Seedmanc/Booru-mass-uploader#22]
It won't upload anything, installed in chrome trough tampermonkey.. but it just won't work.. says error: coudn't upload on every post.

I tried logging in and out / also resetting cache and stuff but no avail.

**Comment by Seedmanc** [comment]
What booru? Does it mention any reasons it couldn't upload? 
Seems to be working here on a booru.org site.

**Comment by owengraven** [comment]
an NSFW booru, catgirls.booru.org

it takes ages to try to upload and then I get this:

[10:54] Started uploading 4 files.
[10:55] Couldn't upload 2idNlFI.jpg: error, undefined .
[10:56] Couldn't upload 2zVQRWL.jpg: error, undefined .
[10:57] Couldn't upload 3aKXsuL.jpg: error, undefined .
[10:58] Couldn't upload 4HJrNG9F20uvwg5eSzFlfIYPKU-0XPIH62zgO0xmT_g.jpg: error, undefined .
[10:58] Finished uploading; 0 uploaded ok + 4 failed = 4 images total.


I tried logging it and out, but I do have 'invisible' images on my homepage since the problem, they are like images but you can't click them or see them, tried contacting support but they are as unresponsive as ever.

**Comment by owengraven** [comment]
I can upload images 1 by 1 via the default uploader, but not with the mass uploader script.

**Comment by Seedmanc** [comment]
That's weird, it works fine here for that booru. Not sure what the invisible images might have to do with it, if it's the images that are mentioned as "(16 posts hidden)" they have negative score so they're hidden by default (threshold can be adjusted in account settings).

One thing I can think of, the uploader might be trying to reach a wrong URL, check if you're accessing booru by http (not https), see if the engine selected is Gelbooru. Check if you're using any VPN or proxies that might have been the problem.

If nothing helps, try to open browser console/developer tools and see the Network tab when uploading, it might show the errors (should be the POST kind of request). See which URL it accesses and what kind of response it gets.

**Comment by owengraven** [comment]
Thanks for the clarification on the hidden images, that has been taken care of, thank you.

The problems with the script persist, I tried uninstall/reinstall tampermonkey and giving it rights for outside URL's again, redownloading and putting a fresh script in there. but to no avail, cleared cache/cookies of websites, logged out and in from the booru. It's running as http:/ so I have no idea.

I have chrome stable, with the latest edition of the script, with the latest version of tampermonkey (4.6.0)
![schermopname 1](https://user-images.githubusercontent.com/2992858/40230262-382e5176-5a97-11e8-82fb-6c46d5fdca16.png)
![schermopname 2](https://user-images.githubusercontent.com/2992858/40230263-384ee8c8-5a97-11e8-87a2-19953cd9964f.png)
![schermopname 3](https://user-images.githubusercontent.com/2992858/40230264-38edc8c6-5a97-11e8-92e5-65204adf81bc.png) 



. 
that is what I get in console.

**Comment by Seedmanc** [comment]
When you're updating/reinstalling the script, what version are you using, the one from the [Releases](https://github.com/Seedmanc/Booru-mass-uploader/releases) section or the [latest one](https://seedmanc.github.io/Booru-mass-uploader/booru.mass.uploader.user.js) directly from the repository? Either way, try a different one and see if it helps.

On your first screenshot it shows the request mid-way, please wait till it finishes (presumably with an error) and make a screenshot again. Note that the "Headers" tab will contain sensitive cookies info at that point so you might want to avoid posting it here and send it to my email instead (seedmanc[at]yahoo.com). If you don't want me to see it at all, roll up the 'Request headers" section before making screenshot. 
Other than that I'd like to see the contents of the "Preview" tab of that request as well. It should show the same kind of page you get after uploading via "Add" manually, but maybe it'll say something about an error there.

Do you have Firefox with Greasemonkey, does it work there?

**Comment by owengraven** [comment]
Sent you the screens by mail, also a huge thank you already for taking time to try and troubleshoot the issue.

Preview page is just blank without data..

I tried on firefox with tampermonkey and greasemonkey having the same results, also tried with the repository version (Download ZIP option) or with the versions from releases. Both do give the same problem on firefox and chrome.  µblock is disactivated, no VPN or proxy setting, not even my DNS is changed from defaults. I have no idea what's causing it.

**Comment by owengraven** [comment]
I finally found the issue, it's my bitdefender antivirus.. for some reason it now has a web protection inside of browsers that can block websites from running. For some reason I can browse booru's fine, but the uploading via the mass uploader is broken and blocked if I leave it on. I turned it off and it works.. 

The fix is to add: "http://catgirls.booru.org/index.php?page=post&s=mass_upload" as an URL exclusion and it works.

Sorry for taking your time, I just didn't know/thought bitdefender would be to blame, also running it on all others pc's I tested.. so yeah.. that why it felt like a network issue.

**Comment by Seedmanc** [comment]
I had a slight feeling it would be something like a 3rd party software, but I didn't put much thought into it as you said you reinstalled and disabled everything. Strange, my script uses the same API as the native booru uploader.

Anyway, glad you figured it out.
