### ISSUE TITLE
Mass uploader button doesn't show up on Draw Friends Booru

### ISSUE THREAD

**Issue by ssmstzo** [Seedmanc/Booru-mass-uploader#25]
Hello,
 I had no issues using the mass uploader recently until today where the button doesn't show up on the front page anymore. I think it may because I did a cookie wipe recently and when I try and reinstall the page just closes. Wondering if you might be able to help. It now doesn't show up on firefox/edge anymore either. Thank you.

**Comment by Seedmanc** [comment]
Seems that even booru.org is now plagued by https.
Fixed.

**Comment by ssmstzo** [comment]
Thank you it worked!
