### ISSUE TITLE
*.booru.org also requires https now

### ISSUE THREAD

**Issue by owengraven** [Seedmanc/Booru-mass-uploader#26]
as the title says, script needs update adding https:/ in front of the include for *.booru.org/index.php*

just wanted to let ya know, for once i could figure it out myself and apply fixes

**Comment by Seedmanc** [comment]
Does it not work as it is now? It has a wildcard there 
`// @include     http*://*.booru.org/index.php*`
seems to be working without any adjustment needed.

**Comment by owengraven** [comment]
it lacks the http*:// part in the beta cors script

**Comment by Seedmanc** [comment]
Indeed. Thanks for the notice, updated.
