### ISSUE TITLE
One little thing you might wanna mention

### ISSUE THREAD

**Issue by owengraven** [Seedmanc/Booru-mass-uploader#3]
Hi,

One thing you might wanna mention is the fact you need to be Logged in to your booru for it to work, or it will give you the error: Wrong user ID - it must be a number.

Wanted to let you know for if you decide to include a F.A.Q or help others if they wonder why it doesn't work.

I'm using it with tampermonkey in chrome, works like a charm, thank you a bazillion times for making it work so well :D

**Comment by Seedmanc** [comment]
Ah yeah I noticed that yesterday but just thought that most people upload stuff when logged in anyway. Perhaps I'll try to make it work anonymously as well if you give me an example of a booru that allows anonymous uploading to test it.

**Comment by owengraven** [comment]
My booru does, catgirls.booru.org (it's NSFW!)

Well I figured the same, but just thought it be nice to add to the description for those who might try it.

**Comment by owengraven** [comment]
btw congrats on the implementation.. it's so much better than before :o I didn't have the skills to fix it, so you're kinda an hero now ;)

**Comment by Seedmanc** [comment]
Haha thanks. It was pretty unexpected to me that the uploader would go down and even more unexpected that I will end up being the one to fix that. Here comes the fame.

I'll look into fixing anonymous uploading later, thanks.

**Comment by Seedmanc** [comment]
Alright, I fixed anonymous uploading and also added indication on the page whether you're logged in. Also fixed restoring previously entered data from cookies.
You can delete the image I posted to your booru for testing now.

**Comment by owengraven** [comment]
Damn you're so fast in updating it, good job man! I wish you the best for anything you might wish for!
