### ISSUE TITLE
[Gelbooru] Mass Uploader page refuses to load

### ISSUE THREAD

**Issue by Tenome** [Seedmanc/Booru-mass-uploader#39]
The console displays this error when trying to load the mass uploader.

Content Security Policy: The page’s settings blocked the loading of a resource at https://seedmanc.github.io/Booru-mass-uploader/js/index.html.js?v=1.4.3 (“script-src”).

**Comment by Seedmanc** [comment]
What browser?

**Comment by Tenome** [comment]
My bad, forgot to state that I'm using the latest Firefox. If I'm the only one with this problem, it might be one of my extensions, but I don't know which one would block it.

**Comment by Seedmanc** [comment]
Works for me on the latest FF. 
But anyway, if you're using it for booru.org based sites, they enforced the captcha on every upload, so unfortunately my script won't work with them anymore.

**Comment by Tenome** [comment]
Ah well, no worries.
