### ISSUE TITLE
Websites included

### ISSUE THREAD

**Issue by ProximaNova** [Seedmanc/Booru-mass-uploader#4]
Add:
// @include http://rule34.xxx/index.php*
// @include http://xbooru.com/index.php*

**Comment by Seedmanc** [comment]
Added. I don't feel like testing it there though, so I'll just take your word that it works there.

**Comment by ProximaNova** [comment]
rule34.xxx and xbooru.com (newer gelbooru software) are [top-level domains](https://en.wikipedia.org/wiki/Top-level_domain) run by booru.org: compared to the majority of [hostname](https://en.wikipedia.org/wiki/Hostname) boorus at *.booru.org (older gelbooru software)

My point is that this script [only works on gelbooru-type sites](http://forum.booru.org/index.php?action=vthread&forum=1&topic=20&page=12#msg5207) (older software versions at most *.booru.org, newer at rule34.xxx, furry.booru.org, and xbooru.com, and newest at gelbooru.com)

Other sites to include:
// @include http://pbooru.com/index.php*
// @include http://safeponi.com/index.php*
