### ISSUE TITLE
option for folder upload

### ISSUE THREAD

**Issue by pokeball99** [Seedmanc/Booru-mass-uploader#5]
i'm wanting to upload my entire folder ( which is ~30k images) to a booru.org booru, and i keep crashing trying to select all of the images, so is it possible to just for you to select a folder and it upload all of its content? i also find it ironic that even though this is a "mass uploader", it can't handle... well mass uploading haha

**Comment by Seedmanc** [comment]
I don't think the original mass uploader would have been able to handle that amount either.  
  I'll try adding a folder upload, but with amounts like these there can be no guarantees. Best bet would be zipping those and sending to a server that would handle unzipping and uploading, but that's outside the scope of my userscript.

Strange, I thought I saw that kind of a ZIP uploader way back then, but I can't find it anymore.

**Comment by pokeball99** [comment]
Would it be able to handle nested folders as well?
also, https://github.com/max-pub/DragLoad/blob/master/DragLoad.js might help, line 95 and down in particular

**Comment by Seedmanc** [comment]
Alright, I added basic support for directory selection via `directory` attribute of the file input tag. It seems to only work in Chrome (tested) and Firefox 42+ (not tested), and I don't know whether that would fix the 30k image problem. It should handle nested folders as well.

**Comment by pokeball99** [comment]
alright, i've just got home and tested out the new version, and i have to say, its doing great, i'm 3.4k out of 38k and haven't run into any problems, i will say that when i select the folder, it takes ~10 seconds or so for it to show the number of files that are selected next to the file select button, but i assume thats just because of the large amount of files i'm trying to upload

**Comment by Seedmanc** [comment]
Awesome then, glad the solution was so simple.
