### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by ProximaNova** [Seedmanc/Booru-mass-uploader#8]
When I am logged in then open the mass upload link I sometimes have to refresh the page 0-2 times for it to login (at &s=mass_upload).

**Comment by Seedmanc** [comment]
Weird, never happens to me. Is your booru any special?

Let's see if other users report the same.

**Comment by ProximaNova** [comment]
It is strange; there doesn't seem to be a pattern:
meme.booru.org - 2 refreshes (2nd test: 0)
redpill.booru.org - 1 refresh (2nd test: 3)
something else - 0 refreshed (2nd test: 0)

**Comment by Seedmanc** [comment]
Made some changes to the .user.js, dunno if they addressed the issue, but you're welcome to update and test it.

Did it happen on both FF and Chrome or you only have one installed?

**Comment by ProximaNova** [comment]
I am using Firefox. Also there is now this unintelligible text that says "You are to a site." above the upload button. And I think this glitch might have to do with previously mass uploading; I'll restart my computer and test again.

**Comment by Seedmanc** [comment]
Weird, that means the scripts in the injected page don't fire. I'm using mostly Opera and Chrome and it doesn't happen to me. There's a slight delay between page injection and scripts working, but they never fail to.

I tried it in FF now and the first time it indeed happened like you said, but after a refresh all went to normal and I couldn't reproduce it anymore. I don't even know if you can debug userscripts in FF, I wasn't able to last I tried.

**Comment by ProximaNova** [comment]
Since it doesn't recognize the login status instantly in FF this part in `index.html` displays "You are to a site." instead of "You are [login status] to a [booru type] site."

``` html
<p style="text-align:center;margin-top:-1em;margin-bottom:-0.33em;">
You are <span class="bold" id="loggedIn"></span> to a <span class="bold" id="current"></span> site.
</p>
```

For the above code snippet: is the bold class acted upon by anything other than the CSS ("font-weight:bold;")? I changed it to:

``` html
You are <b id="loggedIn"></b> to a <b id="current"></b> site.
```

**Comment by Seedmanc** [comment]
Nah, it's just seeing `<b>` with stuff like ids is really weird for me. At my work they do everything with classes, even simply bolding text.

 I wish there was stuff like CSS optimizer that would analyze both CSS and HTML structure to simplify them, but I only know separate approaches.

**Comment by Seedmanc** [comment]
Uploader now shows a spinner during scripts' loading and disables the upload button until they're active.

**Comment by Seedmanc** [comment]
Perhaps this issue is related to #10 where entire page fails to load.

 There's a trick with loading scripts in imported page, when you simply insert the page acquired from some source, its inbuilt scripts don't fire normally. Therefore I loop through page's text reinserting them, which causes them to launch (https://github.com/Seedmanc/Booru-mass-uploader/blob/gh-pages/booru.mass.uploader.user.js#L38) Maybe debugging that part of code would help, but >FF >debugging userscripts

**Comment by Seedmanc** [comment]
The issue was due to the indeterminate order of scripts loading. The recent update should fix it for good https://github.com/Seedmanc/Booru-mass-uploader/raw/gh-pages/booru.mass.uploader.user.js
