### ISSUE TITLE
Newbie to coding: How do I actually instal and use it? 

### ISSUE THREAD

**Issue by Around999People** [Seedmanc/Booru-mass-uploader#9]
Could someone walk me, and any other reader, through how to instal the code into your CSS page, as well as to where the button and other things pop up for use on the booru.

I'll be trying to mess with this until something works. 

Ty in advance!

**Comment by Seedmanc** [comment]
As seen on http://forum.booru.org/index.php?action=vthread&forum=1&topic=20&page=12#msg5432 

> For Chrome, install Tampermonkey https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en
> For Firefox, use Greasemonkey https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/
> 
> After that you can just click the "Raw" link on the .user.js file in my Github repository and the addon will install it for you. Or use this link https://github.com/Seedmanc/Booru-mass-uploader/raw/gh-pages/booru.mass.uploader.user.js
> 
> It should add the "Mass upload" link to your booru's top menu in the right corner.

As seen on the front page of this repository:

![screenshot: booru menu](http://puu.sh/mvB9F/ea5668b606.png)
